### ISSUE TITLE
ImportError: cannot import name 'parent_atom_to_modified' from 'fr3d.data.mapping'

### ISSUE THREAD

**Issue by vreinharz** [BGSU-RNA/fr3d-python#29]
Hi, 

I have been trying to run the latest version as  I usually do :
`python ./fr3d-python/fr3d/classifiers/NA_pairwise_interactions.py --input ../Data/CIF/1S72.cif --output . --category basepair,stacking`

but I get the following import problem
`
Unable to load mappings for modified nucleotides.
Error message: [Errno 20] Not a directory: '/Users/vreinharz/.local/share/virtualenvs/PDB_annot-qLn8FKyH/lib/python3.11/site-packages/fr3d-0.0.1-py3.11.egg/fr3d/data/atom_mappings_refined.txt'
Traceback (most recent call last):
  File "/Users/vreinharz/Projects/RNA_saumon/PDB_annot/Src/./fr3d-python/fr3d/classifiers/NA_pairwise_interactions.py", line 71, in <module>
    from fr3d.data.components import Component
  File "/Users/vreinharz/.local/share/virtualenvs/PDB_annot-qLn8FKyH/lib/python3.11/site-packages/fr3d-0.0.1-py3.11.egg/fr3d/data/__init__.py", line 2, in <module>
  File "/Users/vreinharz/.local/share/virtualenvs/PDB_annot-qLn8FKyH/lib/python3.11/site-packages/fr3d-0.0.1-py3.11.egg/fr3d/data/components.py", line 11, in <module>
ImportError: cannot import name 'parent_atom_to_modified' from 'fr3d.data.mapping' (/Users/vreinharz/.local/share/virtualenvs/PDB_annot-qLn8FKyH/lib/python3.11/site-packages/fr3d-0.0.1-py3.11.egg/fr3d/data/mapping.py)
`

**Comment by cgoliver** [comment]
[possibly related](https://github.com/BGSU-RNA/fr3d-python/issues/32)
